### ISSUE TITLE
The nuget API key has expired and the build fails

### ISSUE THREAD

**Issue by matei-tm** [Topshelf/Topshelf#570]
The nuget API key has expired and the build fails.
The https://github.com/Topshelf/Topshelf/blob/develop/appveyor.yml must be updated with a valid nuget API key.

![image](https://user-images.githubusercontent.com/12191374/81467683-11c5c980-91e3-11ea-83e6-723d66b124fb.png)

```yaml
deploy:
- provider: NuGet
  api_key:
    secure: clmIGjybehEsndMhgboQZAko+nhtGzqlqN9LYndm2xfIhCucksq1YthP71qD8YmS
  artifact: Packages
  on:
    branch: master
- provider: NuGet
  name: Prerelease
  api_key:
    secure: clmIGjybehEsndMhgboQZAko+nhtGzqlqN9LYndm2xfIhCucksq1YthP71qD8YmS
  artifact: Packages
  on:
    branch: develop
```

The latest successful build was on the previous pull request because the publish step is disabled for PR

```yaml
platform: Any CPU
nuget:
  project_feed: true
  disable_publish_on_pr: true
```
